name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*'
    paths-ignore:
      - '**/.gitignore'
      - '**/README.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.134.2'
          extended: true

      - name: Hugo build
        run: hugo

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger watchtower
        shell: bash
        env:
          TOKEN: ${{ secrets.WATCHTOWER_TOKEN }}
          ENDPOINT: ${{ secrets.WATCHTOWER_ENDPOINT }}
        run: |
          curl -i -H "Authorization: Bearer $TOKEN" $ENDPOINT